// Build the in-app help: lift the screenshots out of the Word guide and inline
// them into the HTML the tool ships.
//
// The Word document is the single source of the screenshots. Keeping a second
// copy of them in the repo is how two sets of pictures end up disagreeing about
// what the product looks like, so they live in one place and the build takes
// them from there.
//
// They are inlined as data: URIs rather than written beside the page. The help
// is served either from a folder next to the exe or unpacked from an embedded
// resource, and a relative <img src> only resolves in the first case — a
// single self-contained file works in both, with no second path to keep right.
//
//   node tools/build-help.js
//
// Reads  docs/Fishbowl API Tool - User Guide.docx
//        assets/tool-guide.html          (authored, with empty figure slots)
// Writes assets/tool-guide.built.html    (what ships; generated, do not edit)

const fs = require('fs');
const path = require('path');
const os = require('os');
const { execFileSync } = require('child_process');

const root = path.resolve(__dirname, '..');
const docx = path.join(root, 'docs', 'Fishbowl API Tool - User Guide.docx');
const source = path.join(root, 'assets', 'tool-guide.html');
const target = path.join(root, 'assets', 'tool-guide.built.html');

// Which picture answers which slot.
//
// Keyed on the media part name, because that is stable across edits to the
// document text: Word keeps a part's name once it is embedded. The numbering
// is the order they were first pasted in, which is NOT the order they appear,
// so this table was written by looking at each one.
const SHOTS = {
  'image2.png':  'servers',
  'image3.png':  'connect',
  'image4.png':  'production',
  'image5.png':  'request-body',
  'image6.png':  'capture',
  'image7.png':  'variables',
  'image8.png':  'import',
  'image1.png':  'data-tab',
  'image9.png':  'schema-filter',
  'image10.png': 'completion',
  'image11.png': 'completion-qualified',
  'image12.png': 'response-table',
  'image13.png': 'compare',
  'image14.png': 'rights-chip',
  'image15.png': 'catalog-update',
};

// Shots that are not in the Word guide yet.
//
// The document stays the source for everything it holds. This is for a picture
// taken after the last time it was updated — it lives in docs/screenshots/ so
// the build is reproducible on any machine, rather than reaching on to somebody's
// desktop. Paste it into the guide when convenient and delete the line; the
// document wins if the same slot appears in both.
const EXTRA = {
  'idle': 'docs/screenshots/idle.png',
};

// ── pull the media out of the .docx ─────────────────────────────────────
function mediaFrom(file) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'help-'));
  execFileSync('powershell', ['-NoProfile', '-Command',
    `Add-Type -AssemblyName System.IO.Compression.FileSystem; ` +
    `[IO.Compression.ZipFile]::ExtractToDirectory('${file.replace(/'/g, "''")}','${tmp}')`]);

  const dir = path.join(tmp, 'word', 'media');
  const out = {};
  if (fs.existsSync(dir))
    for (const name of fs.readdirSync(dir))
      out[name] = fs.readFileSync(path.join(dir, name));

  fs.rmSync(tmp, { recursive: true, force: true });
  return out;
}

const media = mediaFrom(docx);
const png = n => 'data:image/png;base64,' + media[n].toString('base64');

// ── fill the slots ──────────────────────────────────────────────────────
let html = fs.readFileSync(source, 'utf8');

const byShot = {};
for (const [file, shot] of Object.entries(SHOTS)) if (media[file]) byShot[shot] = file;

// Loose files, only where the document has nothing for that slot.
const loose = {};
for (const [shot, rel] of Object.entries(EXTRA)) {
  if (byShot[shot]) continue;
  const full = path.join(root, rel);
  if (fs.existsSync(full)) loose[shot] = fs.readFileSync(full);
}

const slots = [...html.matchAll(/data-shot="([a-z-]+)"/g)].map(m => m[1]);
const filled = [];
const empty = [];

for (const shot of slots) {
  const file = byShot[shot];
  const bytes = file ? media[file] : loose[shot];
  if (!bytes) { empty.push(shot); continue; }

  // Replace the slot's placeholder body with the picture, leaving the caption.
  const re = new RegExp(
    '(<figure class="shot" data-shot="' + shot + '">)\\s*(?:<div class="shot-missing">[\\s\\S]*?</div>)?',
    '');
  const uri = 'data:image/png;base64,' + bytes.toString('base64');
  html = html.replace(re, '$1<img alt="" src="' + uri + '">')
              .replace('<figure class="shot" data-shot="' + shot + '">',
                       '<figure class="shot filled" data-shot="' + shot + '">');
  filled.push(shot + ' ← ' + (file ?? EXTRA[shot] + '  (loose file, not in the guide yet)'));
}

fs.writeFileSync(target,
  html.replace('<!-- BUILD-STAMP -->',
    '<!-- Generated by tools/build-help.js from the Word guide. Do not edit. -->'));

// ── report ──────────────────────────────────────────────────────────────
console.log(filled.length + ' of ' + slots.length + ' figures filled\n');
for (const f of filled) console.log('  ' + f);
if (empty.length) {
  console.log('\n  still empty: ' + empty.join(', '));
  console.log('  (these render as a labelled frame, not a broken image)');
}

const unused = Object.keys(media).filter(n => !SHOTS[n]);
if (unused.length) console.log('\n  in the document but not mapped: ' + unused.join(', '));

console.log('\nwrote ' + path.relative(root, target) +
            ' (' + (fs.statSync(target).size / 1024 / 1024).toFixed(2) + ' MB)');
